"""
Django settings for manovastra project Happy Independance Day.

Generated by 'django-admin startproject' using Django 6.0.1.
"""

from pathlib import Path
import os
from decouple import config

# ===================== BASE PATH =====================

BASE_DIR = Path(__file__).resolve().parent.parent

# ===================== CORE SETTINGS =====================

SECRET_KEY = config(
    "SECRET_KEY",
    default="django-insecure-dt$mo%+(_scof5!pp6e9gafb6n9$zczg_0+&w4lp@=q2m)rl)b",
)

DEBUG = config("DEBUG", default=True, cast=bool)

ALLOWED_HOSTS = config(
    "ALLOWED_HOSTS",
    default="localhost,127.0.0.1",
    cast=lambda v: [s.strip() for s in v.split(",")],
)

# Django 4+/6+ needs explicit trusted origins for CSRF, especially in production [web:339]
CSRF_TRUSTED_ORIGINS = config(
    "CSRF_TRUSTED_ORIGINS",
    # include local + production; you can adjust this from env in server
    default="http://127.0.0.1:8000,http://localhost:8000,https://manovastra.net",
    cast=lambda v: [s.strip() for s in v.split(",")],
)

# ===================== APPS =====================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "products",
]

# ===================== MIDDLEWARE =====================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "products.middleware.AdminIPWhitelistMiddleware",  # ✅ custom admin hardening
]

# ===================== URLS / WSGI =====================

ROOT_URLCONF = "manovastra.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "products.context_processors.site_settings",
            ],
        },
    },
]

WSGI_APPLICATION = "manovastra.wsgi.application"

# ===================== DATABASE CONFIGURATION =====================
# Dual Database Setup: PostgreSQL (Production) + SQLite3 (Development)

DATABASE_MODE = config("DATABASE_MODE", default="sqlite")

if DATABASE_MODE == "postgres":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": config("DB_NAME", default="manovastra_db"),
            "USER": config("DB_USER", default="postgres"),
            "PASSWORD": config("DB_PASSWORD", default=""),
            "HOST": config("DB_HOST", default="localhost"),
            "PORT": config("DB_PORT", default="5432"),
        }
    }
    print("✅ Using PostgreSQL Database (Production Mode)")
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
    print("✅ Using SQLite3 Database (Development Mode)")

# ===================== PASSWORD VALIDATION =====================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# ===================== INTERNATIONALIZATION =====================

LANGUAGE_CODE = "en-us"
TIME_ZONE = "Asia/Kolkata"
USE_I18N = True
USE_TZ = True

# ===================== STATIC & MEDIA =====================

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ===================== RAZORPAY =====================

RAZORPAY_KEY_ID = config(
    "RAZORPAY_KEY_ID", default="rzp_live_RtsgUy0nSq28NC"
)
RAZORPAY_KEY_SECRET = config(
    "RAZORPAY_KEY_SECRET", default="EypWUnAiUZcrDnuJ0Rg7o5Zd"
)

# ===================== EMAIL =====================

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="prabashnau@gmail.com")
EMAIL_HOST_PASSWORD = config(
    "EMAIL_HOST_PASSWORD", default="usir ohcs fkhi mijt"
)
DEFAULT_FROM_EMAIL = f"Manovastra <{EMAIL_HOST_USER}>"

# ===================== OTP / MANAGER =====================

OTP_EXPIRY_TIME = 5  # minutes

MANAGER_USERNAME = "manager"
MANAGER_PASSWORD = "manager123"

# ===================== ADMIN PANEL SECURITY =====================

# ✅ Custom Admin URL
ADMIN_URL = "secure-manovastra-admin-2026/"

# ---- Cookie & CSRF behaviour ----
# In development (DEBUG=True, using http://127.0.0.1:8000) we must NOT force secure cookies,
# otherwise CSRF cookie is never sent and every POST returns 403. [web:336]

if DEBUG:
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SAMESITE = "Lax"
    CSRF_COOKIE_SAMESITE = "Lax"
else:
    SESSION_COOKIE_SECURE = True        # Only HTTPS in production
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SAMESITE = "Strict"
    CSRF_COOKIE_SAMESITE = "Strict"

# ✅ Security Headers
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"

# ✅ SSL/HTTPS Settings (for production only)
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
