# Generated by Django 6.0.1 on 2026-01-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='blouse_piece',
            field=models.CharField(default='Included (0.8 meters)', max_length=100, verbose_name='Blouse Piece'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Manovastra', max_length=100, verbose_name='Brand Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='fabric',
            field=models.CharField(default='Pure Silk', max_length=100, verbose_name='Fabric Type'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Image 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Image 3'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Image 4'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Image 5'),
        ),
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=True, verbose_name='In Stock'),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.CharField(default='5.5 meters', max_length=50, verbose_name='Saree Length'),
        ),
        migrations.AddField(
            model_name='product',
            name='occasion',
            field=models.CharField(default='Wedding, Festival, Party', max_length=200, verbose_name='Occasion'),
        ),
        migrations.AddField(
            model_name='product',
            name='review_count',
            field=models.IntegerField(default=0, verbose_name='Number of Reviews'),
        ),
        migrations.AddField(
            model_name='product',
            name='weave_type',
            field=models.CharField(default='Handloom', max_length=100, verbose_name='Weave Type'),
        ),
        migrations.AddField(
            model_name='product',
            name='work_details',
            field=models.CharField(default='Golden Zari Weaving', max_length=200, verbose_name='Work Details'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Main Product Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating_count',
            field=models.IntegerField(default=0, verbose_name='Number of Ratings'),
        ),
    ]
