# Generated by Django 6.0.1 on 2026-01-12 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_blouse_piece_product_brand_product_fabric_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='badge_text',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_5',
        ),
        migrations.AlterField(
            model_name='product',
            name='badge_type',
            field=models.CharField(choices=[('discount', 'Discount'), ('bestseller', 'Bestseller'), ('new', 'New')], default='discount', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='blouse_piece',
            field=models.CharField(default='Included (0.8 meters)', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Manovastra', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='current_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='fabric',
            field=models.CharField(default='Pure Silk', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_bestseller',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.CharField(default='5.5 meters', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='occasion',
            field=models.CharField(default='Wedding, Festival', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.5, max_digits=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='weave_type',
            field=models.CharField(default='Handloom', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='work_details',
            field=models.CharField(default='Zari Work', max_length=200),
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Royal Red', 'Royal Red'), ('Golden Yellow', 'Golden Yellow'), ('Royal Purple', 'Royal Purple'), ('Emerald Green', 'Emerald Green'), ('Royal Blue', 'Royal Blue'), ('Pink Blush', 'Pink Blush'), ('Maroon', 'Maroon'), ('Navy Blue', 'Navy Blue'), ('Orange', 'Orange'), ('Black', 'Black')], max_length=50)),
                ('gradient', models.CharField(editable=False, max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ColorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('order', models.IntegerField(default=0)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productcolor')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
