# Generated by Django 6.0.1 on 2026-01-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='primary_color',
            field=models.CharField(choices=[('Red', 'Red'), ('Gold', 'Gold'), ('Blue', 'Blue'), ('Green', 'Green'), ('Purple', 'Purple'), ('Pink', 'Pink'), ('Orange', 'Orange'), ('Black', 'Black'), ('White', 'White'), ('Maroon', 'Maroon')], default='Red', max_length=50),
        ),
    ]
