# Generated by Django 6.0.1 on 2026-01-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_userprofile_rename_emailotp_userotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('site_name', models.CharField(default='Manovastra', max_length=100)),
                ('tagline', models.CharField(default='Elegance Redefined', max_length=200)),
                ('email', models.EmailField(default='info@manovastra.com', max_length=254)),
                ('phone', models.CharField(default='+91 98765 43210', max_length=15)),
                ('address', models.TextField(default='Bangalore, Karnataka, India')),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('enable_cod', models.BooleanField(default=True)),
                ('free_shipping_above', models.DecimalField(decimal_places=2, default=999, max_digits=10)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
