# Generated by Django 6.0.1 on 2026-01-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_sitesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main title', max_length=200)),
                ('subtitle', models.CharField(help_text='Top subtitle text', max_length=200)),
                ('description', models.TextField(help_text='Banner description')),
                ('image', models.ImageField(help_text='Banner image (1920x600px recommended)', upload_to='banners/')),
                ('button_text_1', models.CharField(default='Shop Now', max_length=50)),
                ('button_link_1', models.CharField(help_text='First button link (e.g., /category/sarees/)', max_length=200)),
                ('button_text_2', models.CharField(blank=True, default='Explore', max_length=50)),
                ('button_link_2', models.CharField(blank=True, help_text='Second button link (optional)', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hero Banner',
                'verbose_name_plural': 'Hero Banners',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
