# Generated by Django 6.0.1 on 2026-01-14 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_herobanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='FestivalBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('festival_name', models.CharField(help_text='Festival name (e.g., Makar Sankranti)', max_length=200)),
                ('festival_tag', models.CharField(help_text='Tag line with emoji (e.g., 🪔 Festival Special)', max_length=100)),
                ('title', models.CharField(help_text='Main title', max_length=200)),
                ('description', models.TextField(help_text='Short description')),
                ('offer_text_1', models.CharField(default='UPTO', help_text='First offer text', max_length=50)),
                ('offer_percentage', models.CharField(default='50%', help_text='Discount percentage', max_length=10)),
                ('offer_text_2', models.CharField(default='OFF', help_text='Second offer text', max_length=50)),
                ('coupon_code', models.CharField(help_text='Coupon code (e.g., SANKRANTI50)', max_length=50)),
                ('banner_image', models.ImageField(help_text='Festival banner image (800x600px)', upload_to='festival_banners/')),
                ('button_text', models.CharField(default='Shop Festival Collection', max_length=100)),
                ('button_link', models.CharField(default='/offers/', help_text='Button link URL', max_length=200)),
                ('bg_color_1', models.CharField(default='#FF6B6B', help_text='Background gradient color 1 (hex)', max_length=7)),
                ('bg_color_2', models.CharField(default='#FFE66D', help_text='Background gradient color 2 (hex)', max_length=7)),
                ('is_active', models.BooleanField(default=True, help_text='Show on homepage')),
                ('start_date', models.DateField(help_text='Festival start date')),
                ('end_date', models.DateField(help_text='Festival end date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Festival Banner',
                'verbose_name_plural': 'Festival Banners',
                'ordering': ['-created_at'],
            },
        ),
    ]
