# Generated by Django 6.0.1 on 2026-01-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_festivalbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='about_text',
            field=models.TextField(default='Your destination for premium Indian ethnic wear. Celebrating tradition with contemporary elegance.', help_text='Footer about text'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_us_link',
            field=models.CharField(default='#', help_text='About Us page link', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='blog_link',
            field=models.CharField(default='#', help_text='Blog page link', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='careers_link',
            field=models.CharField(default='#', help_text='Careers page link', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='contact_us_link',
            field=models.CharField(default='#', help_text='Contact Us page link', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='copyright_text',
            field=models.CharField(default='© 2026 Manovastra. All Rights Reserved.', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='our_story_link',
            field=models.CharField(default='#', help_text='Our Story page link', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='press_link',
            field=models.CharField(default='#', help_text='Press page link', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='privacy_policy_link',
            field=models.CharField(default='#', help_text='Privacy Policy page link', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='refund_policy_link',
            field=models.CharField(default='#', help_text='Refund Policy page link', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='returns_link',
            field=models.CharField(default='#', help_text='Returns & Exchange page link', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='shipping_link',
            field=models.CharField(default='#', help_text='Shipping Info page link', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='size_guide_link',
            field=models.CharField(default='#', help_text='Size Guide page link', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='terms_link',
            field=models.CharField(default='#', help_text='Terms & Conditions page link', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='track_order_link',
            field=models.CharField(default='#', help_text='Track Order page link', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='whatsapp',
            field=models.CharField(default='+919353823619', help_text='WhatsApp number with country code', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='whatsapp_url',
            field=models.URLField(blank=True, help_text='WhatsApp direct link (wa.me/...)', null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='working_hours',
            field=models.CharField(default='Mon - Sat: 10:00 AM - 7:00 PM', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube channel URL', null=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='address',
            field=models.TextField(default='MG Road, Bangalore, Karnataka 560001'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='email',
            field=models.EmailField(default='support@manovastra.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='enable_cod',
            field=models.BooleanField(default=True, help_text='Enable Cash on Delivery'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='free_shipping_above',
            field=models.DecimalField(decimal_places=2, default=999.0, help_text='Free shipping above this amount', max_digits=10),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Instagram profile URL', null=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='logo',
            field=models.ImageField(blank=True, help_text='Website logo', null=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='phone',
            field=models.CharField(default='+91 98765 43210', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
