# Generated by Django 6.0.1 on 2026-01-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_sitesetting_about_text_sitesetting_about_us_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_percent',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='track_order_link',
            field=models.CharField(default='/my-orders/', help_text='Track Order page link', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
