# Generated by Django 6.0.1 on 2026-01-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_orderitem_product_name_alter_orderitem_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refund_pending', 'Refund Pending'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
